#!/bin/bash

#SBATCH --job-name=final_20_int_10_1_segAug9_fulldata
#SBATCH --output=final_h20_int_10_1_segAug9_fulldata.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --mem-per-cpu=20480
#SBATCH --gpus=v100:1
#SBATCH --partition=gpu
#SBATCH --time=48:00:00

module load miniconda
# using your anaconda environment
conda activate visual_force_conda

# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_1_pos --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1020:16_final_data_h_20_int_10_seed_1_pos/checkpoint/6.pt --starting_epoch=7 --prev_min_val=0.120 --bs=64 --seed=1 --use_position_feature=True --n_input_channel=5
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_2_pos --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1022:06_final_data_h_20_int_10_seed_2_pos/checkpoint/4.pt --starting_epoch=5 --prev_min_val=0.115 --bs=64 --seed=2 --use_position_feature=True --n_input_channel=5
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_2_pos --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1022:06_final_data_h_20_int_10_seed_3_pos/checkpoint/4.pt --starting_epoch=5 --prev_min_val=0.123 --bs=64 --seed=3 --use_position_feature=True --n_input_channel=5
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=final_data_h_20_int_10_seed_1_segAug--max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv'  --seed=1 --segmentation_aug=True

# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume4_final_data_h_20_int_10_seed_1_segAug --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Mar0823:19_resume3_final_data_h_20_int_10_seed_1_segAug/checkpoint/3.pt --starting_epoch=4 --prev_min_val=0.160 --seed=1 --segmentation_aug=True
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume3_final_data_h_20_int_10_seed_2_segAug --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Mar0823:19_resume2_final_data_h_20_int_10_seed_2_segAug/checkpoint/2.pt --starting_epoch=3 --prev_min_val=0.161 --seed=2 --segmentation_aug=True
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume4_final_data_h_20_int_10_seed_3_segAug --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Mar0823:19_resume3_final_data_h_20_int_10_seed_3_segAug/checkpoint/3.pt --starting_epoch=4 --prev_min_val=0.183 --seed=3 --segmentation_aug=True

python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=final_data_h_20_int_10_seed_1_segAug9_fulldata --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --seed=1 --segmentation_aug=True #--use_position_feature=True --n_input_channel=5 
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=final_data_h_20_int_10_seed_1_mlp --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --seed=1 --network=mlpresnet


# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_2 --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1018:43_final_data_h_20_int_10_seed_2/checkpoint/4.pt --starting_epoch=5 --prev_min_val=0.113 --bs=64 --seed=2
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_3 --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1018:43_final_data_h_20_int_10_seed_3/checkpoint/6.pt --starting_epoch=7 --prev_min_val=0.121 --bs=64 --seed=3


# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_1_posSpeed --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1022:03_final_data_h_20_int_10_seed_1_posSpeed/checkpoint/4.pt --starting_epoch=5 --prev_min_val=0.115 --bs=64 --seed=1 --use_position_feature=True --n_input_channel=5 --speed_augmentation=True
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_2_posSpeed --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1022:03_final_data_h_20_int_10_seed_2_posSpeed/checkpoint/4.pt --starting_epoch=5 --prev_min_val=0.114 --bs=64 --seed=2 --use_position_feature=True --n_input_channel=5 --speed_augmentation=True
# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_3_posSpeed --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1021:57_final_data_h_20_int_10_seed_3_posSpeed/checkpoint/6.pt --starting_epoch=7 --prev_min_val=0.111 --bs=64 --seed=3 --use_position_feature=True --n_input_channel=5 --speed_augmentation=True


# python main.py --train_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --valid_data_dir=/vast/palmer/home.grace/yz2379/project/Data/final_data_segmented/ --note=resume_final_data_h_20_int_10_seed_2 --max_epoch=100 --env_type=real_world_yz --n_history=20 --history_interval=10 --train_csv_fn='train_result.csv' --valid_csv_fn='val_result.csv' --load_model=/vast/palmer/home.grace/yz2379/VisionForceEstimator/runs/Feb1018:43_final_data_h_20_int_10_seed_2/checkpoint/4.pt --starting_epoch=5 --prev_min_val=0.113 --bs=128 --seed=2 #--use_position_feature=True --n_input_channel=5 --speed_augmentation=True

#--use_position_embedding=True --position_embedding_dim=20 --n_input_channel=23 --bs=16

